[package]
name = "bowst"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.14", features = ["blocking"] }
quick-xml = { version = "0.37.2" }
serde_json = { version = "1.0.140" }
serde = { version = "1.0.219", features = ["derive"] }